#!/bin/bash

###############################################################
### Script that should (should) let you do MLB link pushes  ###
###############################################################

YEAR=$1
MNTH=$2
DAY1=$3
DAY2=$4
DAY3=$5
USER=$6
CURR_DIR=`pwd`
HOST=`uname -n`

if [[ "$1" == "-help" || "$1" == "-h" || "$1" == "" || $# < 6 ]]; then
	echo "################################################################################"
	echo "This script is to help automate the MLB Link push process."
	echo "It should be run like below on sce28.mm3 only"
	echo "EX. /opt/bin/AutoMLBLinkpush <Year> <Month> <DAY1> <DAY2> <DAY3 or NONE> <USER>"
	echo "You will only be allowed to push the max three days at one time"
	echo "Day 3 can be optional in case that would only leave a day gap"
	echo "################################################################################"
	exit 0
else
	if [[ $# == 6 ]]; then
		if [[ $CURR_DIR != "/opt/bin" || $HOST != "sce28" ]]; then
			echo "please run script from /opt/bin on sce28 only"
			exit 0
		elif [[ -d /export/home/$USER/archive_out_mlb ]]; then
			if [[ $DAY3 == "none" || $DAY3 == "NONE" || $DAY3 == "None" ]]; then
				### Create the .out files 
				echo "You have Day 3 set to $DAY3, so you will only push two days worth of links"
				echo "The days you are pushing are, $DAY1 - $DAY2"
				echo "ls /lsnas04/data/PROD/video/mlbam/$YEAR/$MNTH/$DAY1 | grep -v _x | grep -v MLB_VIDEO | grep -v AUDIO > /export/home/$USER/$YEAR$MNTH$DAY1.out"
				echo "ls /lsnas04/data/PROD/video/mlbam/$YEAR/$MNTH/$DAY2 | grep -v _x | grep -v MLB_VIDEO | grep -v AUDIO > /export/home/$USER/$YEAR$MNTH$DAY2.out"
				ls /lsnas04/data/PROD/video/mlbam/$YEAR/$MNTH/$DAY1 | grep -v _x | grep -v MLB_VIDEO | grep -v AUDIO > /export/home/$USER/$YEAR$MNTH$DAY1.out
				ls /lsnas04/data/PROD/video/mlbam/$YEAR/$MNTH/$DAY2 | grep -v _x | grep -v MLB_VIDEO | grep -v AUDIO > /export/home/$USER/$YEAR$MNTH$DAY2.out

				### Now we will do a wc on the newly created .out files to compare them to whats
				### on msnas101 if they are equal, great if not cannot push have to make sure
				### what the differences are.
				sleep 3
				echo "Get the amount of games played on $DAY1" 
				DAY1_COUNT=`cat /export/home/$USER/$YEAR$MNTH$DAY1.out | wc -l`
				echo "Get the amount of games played on $DAY2" 
				DAY2_COUNT=`cat /export/home/$USER/$YEAR$MNTH$DAY2.out | wc -l`
				echo "Get the amount of games from msnas101 for $DAY1"
				D1MS101_COUNT=`ls /msnas101/mlb/mlbam/$YEAR/$MNTH/$DAY1 | grep MLB_GAME_VIDEO | grep -v _x | wc -l`
				echo "Get the amount of games from msnas101 for $DAY2"
				D2MS101_COUNT=`ls /msnas101/mlb/mlbam/$YEAR/$MNTH/$DAY2 | grep MLB_GAME_VIDEO | grep -v _x | wc -l`


		fi
	fi
fi

